### ISSUE TITLE
1.17 Incompatibility w/ DimDoors

### ISSUE THREAD

**Issue by micahflack** [QuiltServerTools/HeyThatsMine#13]
Not necessarily the fault of HTM - but there is an existing incompatibility with DimDoors 4.0.0-beta for Fabric 1.17

The following error is generated when attempting to launch a Fabric 1.17 server:

`
[04:27:06] [main/FATAL]: Mixin apply failed htm.mixins.json:events.ExplosionMixin -> net.minecraft.class_1927: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("NEW") on net/minecraft/class_1927::HTMExplosionProtectionCheck with priority 1000 cannot inject into net/minecraft/class_1927::method_8350(Z)V merged by org.dimdev.dimdoors.mixin.ExplosionMixin with priority 1000 [PREINJECT Applicator Phase -> htm.mixins.json:events.ExplosionMixin -> Prepare Injections -> -> handler$zgc000$HTMExplosionProtectionCheck(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare] org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("NEW") on net/minecraft/class_1927::HTMExplosionProtectionCheck with priority 1000 cannot inject into net/minecraft/class_1927::method_8350(Z)V merged by org.dimdev.dimdoors.mixin.ExplosionMixin with priority 1000 [PREINJECT Applicator Phase -> htm.mixins.json:events.ExplosionMixin -> Prepare Injections -> -> handler$zgc000$HTMExplosionProtectionCheck(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare] at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.lambda$static$1(BlockExplodeCallback.java:14) ~[htm-1.1.2.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:41) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:37) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:61) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.<clinit>(BlockExplodeCallback.java:13) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.listeners.WorldEventListener.init(WorldEventListener.java:23) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.HTM.onInitialize(HTM.java:33) ~[htm-1.1.2.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-server-launch.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-server-launch.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) [fabric-server-launch.jar:?] at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?] [04:27:06] [main/INFO]: Loaded door json from /home/amp/.ampdata/instances/CaveMinecraft/Minecraft/./config/dimdoors/doors/iron_dimensional_door.json with id dimdoors:iron_dimensional_door [04:27:06] [main/INFO]: Loaded door json from /home/amp/.ampdata/instances/CaveMinecraft/Minecraft/./config/dimdoors/doors/quartz_dimensional_door.json with id dimdoors:quartz_dimensional_door [04:27:06] [main/INFO]: Loaded door json from /home/amp/.ampdata/instances/CaveMinecraft/Minecraft/./config/dimdoors/doors/oak_dimensional_door.json with id dimdoors:oak_dimensional_door [04:27:06] [main/INFO]: Loaded door json from /home/amp/.ampdata/instances/CaveMinecraft/Minecraft/./config/dimdoors/doors/gold_dimensional_door.json with id dimdoors:gold_dimensional_door [04:27:07] [main/FATAL]: Failed to start the minecraft server java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'htm'! at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?] at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?] at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.lambda$static$1(BlockExplodeCallback.java:14) ~[htm-1.1.2.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:41) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:37) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:61) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.<clinit>(BlockExplodeCallback.java:13) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.listeners.WorldEventListener.init(WorldEventListener.java:23) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.HTM.onInitialize(HTM.java:33) ~[htm-1.1.2.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?] ... 17 more Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [htm.mixins.json:events.ExplosionMixin] from phase [DEFAULT] in config [htm.mixins.json] FAILED during APPLY at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.lambda$static$1(BlockExplodeCallback.java:14) ~[htm-1.1.2.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:41) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:37) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:61) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.<clinit>(BlockExplodeCallback.java:13) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.listeners.WorldEventListener.init(WorldEventListener.java:23) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.HTM.onInitialize(HTM.java:33) ~[htm-1.1.2.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?] ... 17 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("NEW") on net/minecraft/class_1927::HTMExplosionProtectionCheck with priority 1000 cannot inject into net/minecraft/class_1927::method_8350(Z)V merged by org.dimdev.dimdoors.mixin.ExplosionMixin with priority 1000 [PREINJECT Applicator Phase -> htm.mixins.json:events.ExplosionMixin -> Prepare Injections -> -> handler$zgc000$HTMExplosionProtectionCheck(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare] at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?] at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?] at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.lambda$static$1(BlockExplodeCallback.java:14) ~[htm-1.1.2.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:41) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:37) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:61) ~[94e7c517-a38b-49c4-8c23-c5ca8b1740dc.jar:?] at com.github.fabricservertools.htm.events.BlockExplodeCallback.<clinit>(BlockExplodeCallback.java:13) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.listeners.WorldEventListener.init(WorldEventListener.java:23) ~[htm-1.1.2.jar:?] at com.github.fabricservertools.htm.HTM.onInitialize(HTM.java:33) ~[htm-1.1.2.jar:?] at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?] ... 17 more
`

See more here: [DimDoors Issue #205](https://github.com/DimensionalDevelopment/DimDoors/issues/205)

**Comment by yitzy299** [comment]
This isn't an HTM issue - dimdoors is overwriting the method. There's nothing we can do about that
